/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The FileReadDto model module.
 * @module model/FileReadDto
 * @version v0
 */
export default class FileReadDto {
  /**
   * Constructs a new <code>FileReadDto</code>.
   * @alias module:model/FileReadDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FileReadDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FileReadDto} obj Optional instance to populate.
   * @return {module:model/FileReadDto} The populated <code>FileReadDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FileReadDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('link'))
        obj.link = ApiClient.convertToType(data['link'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
FileReadDto.prototype.id = undefined;

/**
 * @member {String} link
 */
FileReadDto.prototype.link = undefined;

/**
 * @member {String} type
 */
FileReadDto.prototype.type = undefined;

