/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The FileGetDto model module.
 * @module model/FileGetDto
 * @version v0
 */
export default class FileGetDto {
  /**
   * Constructs a new <code>FileGetDto</code>.
   * @alias module:model/FileGetDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FileGetDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FileGetDto} obj Optional instance to populate.
   * @return {module:model/FileGetDto} The populated <code>FileGetDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FileGetDto();
      if (data.hasOwnProperty('file'))
        obj.file = ApiClient.convertToType(data['file'], ['Blob']);
    }
    return obj;
  }
}

/**
 * @member {Array.<Blob>} file
 */
FileGetDto.prototype.file = undefined;

