/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The JwtAuthenticationResponse model module.
 * @module model/JwtAuthenticationResponse
 * @version v0
 */
export default class JwtAuthenticationResponse {
  /**
   * Constructs a new <code>JwtAuthenticationResponse</code>.
   * Ответ c токеном доступа
   * @alias module:model/JwtAuthenticationResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>JwtAuthenticationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JwtAuthenticationResponse} obj Optional instance to populate.
   * @return {module:model/JwtAuthenticationResponse} The populated <code>JwtAuthenticationResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new JwtAuthenticationResponse();
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
    }
    return obj;
  }
}

/**
 * Токен доступа
 * @member {String} token
 */
JwtAuthenticationResponse.prototype.token = undefined;

