/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UserCreateEditDto model module.
 * @module model/UserCreateEditDto
 * @version v0
 */
export default class UserCreateEditDto {
  /**
   * Constructs a new <code>UserCreateEditDto</code>.
   * @alias module:model/UserCreateEditDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserCreateEditDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserCreateEditDto} obj Optional instance to populate.
   * @return {module:model/UserCreateEditDto} The populated <code>UserCreateEditDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserCreateEditDto();
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} password
 */
UserCreateEditDto.prototype.password = undefined;

/**
 * @member {String} username
 */
UserCreateEditDto.prototype.username = undefined;

/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
UserCreateEditDto.RoleEnum = {
  /**
   * value: "ADMIN"
   * @const
   */
  ADMIN: "ADMIN",

  /**
   * value: "USER"
   * @const
   */
  USER: "USER"
};
/**
 * @member {module:model/UserCreateEditDto.RoleEnum} role
 */
UserCreateEditDto.prototype.role = undefined;

