/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UserLoginDto model module.
 * @module model/UserLoginDto
 * @version v0
 */
export default class UserLoginDto {
  /**
   * Constructs a new <code>UserLoginDto</code>.
   * @alias module:model/UserLoginDto
   * @class
   * @param password {String} 
   * @param username {String} 
   */
  constructor(password, username) {
    this.password = password;
    this.username = username;
  }

  /**
   * Constructs a <code>UserLoginDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserLoginDto} obj Optional instance to populate.
   * @return {module:model/UserLoginDto} The populated <code>UserLoginDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserLoginDto();
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} password
 */
UserLoginDto.prototype.password = undefined;

/**
 * @member {String} username
 */
UserLoginDto.prototype.username = undefined;

